# Site
title: Issie's Blog
subtitle: About coding、reading、thinking、writing and creating
description: 关于编程、阅读、思考、写作和创作
author: Issie Lv
language: zh-CN
timezone: Asia/Shanghai
url: https://issieart.com

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md
default_layout: post
date_format: YYYY-MM-DD

# Theme
theme: issie

# Index Generator
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Pagination
per_page: 10
pagination_dir: page
