theme: jekyll-theme-minimal
title: issie's Blog
description: "06年程序员，喜欢创造、阅读，提升个人生产力，对美的东西有着不懈追求，目前的目标是希望能做一款属于自己的产品；感兴趣的开发方向是: 平台、基础设施构建; 联系方式，email: xxin778@163.com，vx: issie_x"
show_downloads: false
google_analytics:
