theme: jekyll-theme-minimal
title: issie's Blog
description: about coding, reading, thinking, writing and creating.
show_downloads: false
google_analytics:
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: Issie Lv
  email: xxin778@163.com
